shallow_clone: true

os:
  - Visual Studio 2019

environment:
  matrix:
    - TOOLSET: vs2019

platform:
    - x64
    - Win32

configuration:
    - Debug
    - Release
    - Retail

install:
    - set QTDIR_VS2019_x64=C:\Qt\6.0.1\msvc2019_64
    - set QTDIR_VS2019_x86=C:\Qt\6.0.1\msvc2019 
    - set PATH=C:\projects\luaforwindows\files;%QTDIR_VS2019_x64%\bin;%PATH%
    - git clone --depth 1 https://github.com/milostosic/build   ..\build
    - git clone --depth 1 https://github.com/milostosic/rbase   ..\rbase
    - git clone --depth 1 https://github.com/milostosic/rdebug  ..\rdebug
    - git clone --depth 1 https://github.com/milostosic/DIA     ..\DIA
    - git clone --depth 1 https://github.com/milostosic/luaforwindows ..\luaforwindows
    - ..\build\tools\bin\windows\genie --file=genie\genie.lua %TOOLSET%

build:
  project: ../.build/windows/$(TOOLSET)/rqt/projects/rqt.sln
